name: 📚 Suggest a New Book
description: Recommend a new technical book to add to the reading list.
title: "[Book Suggestion] "
labels: ["book suggestion"]
body:
  - type: input
    id: book_name
    attributes:
      label: Book Name
      placeholder: e.g., Designing Data-Intensive Applications
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why This Book?
      placeholder: Why should we include it?
